apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: utils
  namespace: paas-shack
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: utils
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: utils
    spec:
      containers:
      - env:
        - name: SERVICES
          value: services/**/*.service.js
        envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: secrets
        image: ghcr.io/paas-shack/utils:main
        imagePullPolicy: Always
        name: utils
        resources:
          limits:
            cpu: 500m
            memory: 256M
          requests:
            cpu: 50m
            memory: 50M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: utils
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule